modified wish to only take server name as argumnet

diff --git a/scripts/.local/bin/wish b/scripts/.local/bin/wish
--- a/scripts/.local/bin/wish
+++ b/scripts/.local/bin/wish
@@ -1,11 +1,32 @@
 #! /usr/bin/env bash
-CONFIG_LOCATION="$HOME/.config/sesshin/servers.yml"
-SERVER=$(yq -r ".[] | select(has(\"ssh\")) |.name" $CONFIG_LOCATION | gum choose --header="Choose server: ")
-INSTANCE_ID=$(yq -r ".[] | select(.name == \"$SERVER\") | .instance" $CONFIG_LOCATION)
-PROFILE=$(yq -r ".[] | select(.name == \"$SERVER\") | .profile" $CONFIG_LOCATION)
-REGION=$(yq -r ".[] | select(.name == \"$SERVER\") | .region" $CONFIG_LOCATION)
-SSH_USER=$(yq -r ".[] | select(.name == \"$SERVER\") | .ssh.user" $CONFIG_LOCATION)
-PORT=$(yq -r ".[] | select(.name == \"$SERVER\") | .ssh.port" $CONFIG_LOCATION)
+if ! command -v yq &> /dev/null; then
+    echo "Error: Required command 'yq' not found in PATH."
+    exit 1
+fi
+echo $SESSHIN_DIR
+if [ -z $SESSHIN_DIR ]; then
+    echo "Error: No configuration directory found. Please set \$SESSHIN_DIR"
+    exit 1
+fi
+
+CONFIG_FILE="$SESSHIN_DIR/servers.yml"
+if [ ! -f "$CONFIG_FILE" ]; then
+    echo "Error: servers.yml not found in the configuration directory"
+    exit 1
+fi
+
+if [ $# -lt 1 ]; then
+    echo "Usage: $0 <INSTANCE_NAME>"
+    exit 1
+fi
+
+SERVER="$1"
+
+INSTANCE_ID=$(yq -r ".[] | select(.name == \"$SERVER\") | .instance" $CONFIG_FILE)
+PROFILE=$(yq -r ".[] | select(.name == \"$SERVER\") | .profile" $CONFIG_FILE)
+REGION=$(yq -r ".[] | select(.name == \"$SERVER\") | .region" $CONFIG_FILE)
+SSH_USER=$(yq -r ".[] | select(.name == \"$SERVER\") | .ssh.user" $CONFIG_FILE)
+PORT=$(yq -r ".[] | select(.name == \"$SERVER\") | .ssh.port" $CONFIG_FILE)
 
 if [ "$SSH_USER" == "null" ] || [ "$PORT" == "null" ]; then
     echo "Error: SSH user or port not defined for instance"
